### ISSUE TITLE
User Story: List of recipes

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#1]
## Value proposition

As a user
I want to have an overview of all recipes
so that I get an inspiration of a meal I like to cook.

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/98de905b-63e8-4098-b17a-e65a33e97d74)

## Acceptance criteria

- [x] on the top of the homepage, there is a title "Fork Yeah" 
- [x] On the homepage, there is a list of recipes displayed
- [x] Each recipe in the list includes the following details: 
1. name 2. picture 
- [x] If there is an issue loading the recipe data from the source, 
an error message is displayed to the user
- [x] The recipe list is vertically scrollable

## Tasks

- [x] Create the feature branch recipe list
- [x] Implement the error handling logic to display an error message
- [x] Create the recipe component which renders...
- the name of the recipe
- the image of the meals/recipe
- [x] create the component recipe list
- [x] map through the fetched list of recipes and render a Recipe component for each recipe
- [x] render the Recipe List in the index.js or whatever the file is called

```

**Comment by JessicaLoers** [comment]
**Hey @feivlinus @vlatkojuric @Shahab-Ziaeian** 🍴

nice first User Story - well done ✨

In the description there is a title "Fork Yeah".
This UI element should please be listed as an item in the AC.

**Comment by vlatkojuric** [comment]
Hey Jessica, thank you for the advice, we have done the update, hope everything is ok now.

**Comment by feivlinus** [comment]
![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/bb0f8810-f0f7-42af-bfca-2181541c4c09)
