### ISSUE TITLE
Update a recipe

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#10]
## Value proposition

As a user, 
I want to update an existing recipe so that I can make changes to the ingredients, instructions, and other details.

## Description

Left image only shows the pen icon which leads to the editing. Ignore the rest of the left side.
Right side of the image is relating to this [user story](https://github.com/feivlinus/fork-yeah/issues/4). We want to reuse the create form.

![Untitled-2023-11-23-1207](https://github.com/feivlinus/fork-yeah/assets/145024927/505c3bab-0865-4cd3-945e-95778125f363)

## Acceptance Criteria

- [ ] I should see an "Update Recipe" button or option
- [ ] Clicking the "Update Recipe" button should open a page or form where I can modify the recipe details
- [ ] I should be able to change the recipe title, description, ingredients, instructions, cooking time, and other relevant fields
- [ ] I should be able to save the changes and have them reflected in the recipe details page
- [ ] If you click the cancel button, you will be directed to the details page again

## Tasks

- [ ] Refactor the create-form to use is for editing
- [ ] Display the existing recipe details in the edit form
- [ ] Allow users to modify the recipe title, description, ingredients, instructions, cooking time, and other relevant fields
- [ ] Implement a update function to store the data 
- [ ] Update the recipe details page to reflect the saved changes

**Comment by GoekhanAgkurt** [comment]
Hey Team Fork-Yeah,

great work! 

We have some suggestions for you:

- try to have the same order of the inputs and Details on the Details Page. (Example: the image should come before the  duration time in your Edit form)

- In your Wireframe  we see a "X" Button to cancel the Edit Process, but you do not mention it in your AC and Tasks. Maybe you want to add the cancel Button, because it is a useful feature. 

- try to make your Wireframe more  understandable by naming the fields in the Detail Page. E.g.: Description, Ingredients...


Keep up the good work!!! 🙌

**Comment by feivlinus** [comment]
@GoekhanAgkurt Thank for your suggestions! We added additional information at the description and changed the wireframe.
A abort "x" button will be added in future since its part of just a styling. Its not a button its a link. We will change the appearance in a extra user story for styling in future.

**Comment by Roland-Hufnagel** [comment]
Hi Fork-Yeah! Great Work! Just a few suggestions:
- If the abord "x" button is a future feature, remove it from the wireframe. 
- In your AC the behaviour of the cancel-button is missing
- Since you want to reuse your create-form you could define this in your tasks: 'Refactor the create-form to use is for editing...'
-

**Comment by Shahab-Ziaeian** [comment]
Thank you for your suggestions Roland! We made the changes and fixed the wireframe.

**Comment by Julia-Pickel** [comment]
LGTM – great work !! 

![image](https://github.com/feivlinus/fork-yeah/assets/145296722/62f7669e-6d5d-4454-9ffe-f2da731304d4)

Keep it up 🍕 -Team 🙌
