### ISSUE TITLE
Mark Recipes as Favorites

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#11]
## Value proposition

As a user
I want to mark my recipes as favorites
so i can access the recipes i like or cook regularly easier

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/244144e3-e5fe-4b24-8af4-1102460bfe50)
![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/1ab8a95d-7aa7-4ac3-9fd0-e4ad131bd380)

## Acceptance criteria

- [ ] If you open the app and see the recipe list on every recipe is a favorite button above the picture at the top right
- [ ] If you open the recipe details page there is a favorite button under the picture
- [ ] if you click on the favorite button at recipe list or recipe details the recipe gets marked as favorite
- [ ] When you click on the icon its appearance changes according to its favorite status 

## Tasks

- [ ] create a new branch
- [ ] make a button with a icon inside
- [ ] make the button reactive so it can change its appearance depending of a click
- [ ] store the information of a favorite recipe

**Comment by Roland-Hufnagel** [comment]
Hi. This is a good US 💪. If you want to improve it a bit, you could go a bit into detail, how to store the information of the favorite recipe.
