### ISSUE TITLE
Favorite recipes page

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#12]
## Value proposition

As a user 
i want to see all my favorite recipes
so i can choose easily between them to get an i idea what i want to cook today

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/f3790d1f-433b-4629-b05b-974dd70611c4)

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/a1ce2b12-e52d-4129-9d71-82e150ea20fb)

## Acceptance criteria

- [ ] Clicking on the heart icon at the navigation opens the favorite page 
- [ ] The heart icon at the navigation changes to indicate where you at after clicking on it
- [ ] Recipes can be removed from the favorite page by toggling on the recipes heart icon
- [ ] Clicking on a recipe leads to its recipe details page

## Tasks

- [ ] append the navigation with a heart icon and link that leads to the favorite page 
- [ ] render all favorite recipes
- [ ] implement the favorite toggle feature
- [ ] implement color change of heart icon at the navigation when favorite page is open

**Comment by ykolomytseva** [comment]
Privet🎄✨ ❄    Very nice user story and here are just some suggestions from my team:

- The acceptance criteria should be written from the user's perspective. It helps ensure that the feature or user story meets the user's expectations and requirements. That's why instead of using "I," try something like: 'When clicking on the heart icon in the navigation, the favorite page should open' and etc.
- We also recommend you to be more specific about your tasks. Try something like this: 'Add a heart icon to the navigation bar. Create a link that, when clicked, opens the favorite page.'

**Comment by feivlinus** [comment]
Privet Yana 🤓
Thank you for your review!

We changed the acceptance criteria and tried to be more precise with the first task.
