### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#13]
## Value proposition

As a user
I want to have a navigation bar
In order to navigate quickly to the different pages of my app.

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/d495cb16-59a6-40d1-a4b6-9d31713cb19a)

## Acceptance criteria

- [x] A NavBar is visible on the bottom of every page 
- [x] It contains different links directing the user to the relative pages 
- [x] There is a home icon and a plus icon at the navigation bar. 
- [x] if you click on the home icon you will be directed to the home page (first page)
- [x] if you click on the plus icon you will be directed to the create recipe page

## Tasks

- [x] create a new branch
- [x] create a component NavigationBar.js
- [x] create links to the corresponding pages (home page, create recipe)
- [x] apply basic styling

**Comment by luederb** [comment]
Hey Fork yeah! - Team. 
great user story 👍
We are wondering though, if it could be a useful feature for the user, to indicate, on which page the user is currently on. The active page could have an highlighted navbar icon for example.

**Comment by Shahab-Ziaeian** [comment]
Hey Lüder, thank you for your suggestion. We had this point in mind, but decided to implement this feature on a separated user story with other styling topics. 😊

**Comment by luederb** [comment]
Good to see that you keep the user stories short and simple 💪
Well done, approved ✅
