### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by vlatkojuric** [feivlinus/fork-yeah#14]
## Value proposition

As a user, I want to upload images for my newly created recipes to enhance the visual appeal and provide a better understanding of the dish.

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/145024927/faa9b65a-a624-4151-a145-8011896ba9d1)

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/06b05bef-0d63-49ab-8b87-56eea56275c8)

## Acceptance criteria

- [x] "Upload Image" button should be seen an at the create recipe form
- [x] Clicking the "Upload Image" button should open a file picker 
- [x] One image, in the supported formats (e.g., JPEG, PNG, GIF), should be able to be selected for the upload
- [x] When a image is uploaded for the recipe there should be a file name listed when you edit (update recipe) the recipe
- [ ] The uploaded image can be deleted by clicking on the trash bin icon next to its listed file name

 NOTE : we will use our Create Recipe component and do small changes for the Form to adapt it for this user story

## Tasks

- [x] Create a feature branch 
- [x] set up Cloudinary
- [x] Create a Upload Image button
- [x] Implement a file picker for selecting images
- [x] Store the uploaded image in a suitable location ( cloud storage)
- [ ] Provide an option to remove uploaded images from the recipe creation form
- [x] Implement error handling for image upload failures or invalid file formats

**Comment by Roland-Hufnagel** [comment]
Good job and fine US. 💪
One suggestion: If you already know that you will use Cloudinary for image upload, you can mention this in your tasks.

**Comment by BirkBee** [comment]
LGTM 🙌  very nice work! 🚀
