### ISSUE TITLE
Add and delete ingredients

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#16]
## Value proposition

As a user
I want to be able to add and delete ingredients to my recipes
so that I can revise my recipes according to my taste.

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/145270267/4e6dcb8f-77b1-4943-a537-4fe59cbefe9d)

## Acceptance criteria

- [x] On the edit form page there should be an add and delete icon next to the 
        ingredient (right side) 
- [x] Clicking the add icon should open two new empty input fields under 
        the existing one/ones
- [x] Clicking the delete icon should delete the targeted ingredient with its 
        related amount 
- [x] After making changes they have to be saved by clicking the Save 
       changes button at the bottom 
- [x] Clicking the Cancel button will redirect back to the details page 

NOTE: The create recipe form will be extended with this user story

## Tasks

- [x] create a branch 
- [x] edit the edit form with the add and delete feature 
- [x] Add the new input fields values to the requested form data, so that the 
       data can be stored
- [x] Update the recipe details page to reflect the saved changes

**Comment by BirkBee** [comment]
Very nice US, LGTM 🙌 
You could maybe also have two US instead of one for add and delete. But that's just a suggestion, I'm sure you can also do both in one 🚀
