### ISSUE TITLE
User Story: Recipe details

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#2]
## Value proposition

As a cooking enthusiast,
I want to see all information about a specific recipe 
so that I can cook the chosen recipe.   

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/d6c254a8-7b34-47fa-b341-6a5b36cf719e)

## Acceptance criteria

- [x] clicking a recipe on the recipe list leads to the related details page of the recipe
- [x] the recipe details page displays the title, an image of the finished dish, a description of the cooking process, preparation time , and a list of ingredients with quantities.
- [x] a link that redirects the user back to the overview of all recipes

## Tasks

- [x] create the feature branch recipe-details-page
- [x] create the recipe details page pages/recipe/[id].js
- [x] render the recipes picture, title, description, preparation time and ingredients with their amount
- [x] add a link for each recipe at the recipe list which leads to each recipe detail page

```

**Comment by JessicaLoers** [comment]
Mhhhh... Pizza Soup is my favourite meal 🍕 

**Hey @feivlinus @vlatkojuric @Shahab-Ziaeian** 

Why are all your criteria formulated as questions. 🤷‍♀️

>at the details title, preparation time, description and ingredients with their amount can be seen?

⬆️ This sentence is worded somewhat strangely, and I guess the word **page** is missing. 

_suggestion:_
- The recipe details page displays the title, an image of the finished dish, preparation time, a description of the cooking process, and a list of ingredients with quantities.

**Otherwise toppy User Story.** ✌️

**Comment by vlatkojuric** [comment]
Hey Jessica, to be honest we don't know,I guess it stuck to our eyes from the template lol, thank you for noticing it and for the kind suggestion :)

**Comment by Julia-Pickel** [comment]
Nice user story!! Looks good to us 🥳
