### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by feivlinus** [feivlinus/fork-yeah#23]
## Value proposition

As a user
I want to have a appealing design
to have a good experience while using the app

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/96fb99e0-58f5-4670-8f49-23b904f41527)

[Font open sans](https://fonts.google.com/specimen/Open+Sans?preview.text=Fork%20yeah%20Pizza%20soup
)
- Color palette
- Font: open sans
- Top bar with title of page and logo
- Style for the Create/Add Form
- Style for the Recipe List
- Style for Recipe details
- Style for Navigation

## Acceptance criteria

- [x] All colors from the color palette are applied
- [x] The open font is in use everywhere
- [x] Topbar is on every page
- [x] All buttons and icons have the same color shema based on the color palette
- [x] All buttons are standardized: shape, border-radius, text color

## Tasks

- [x] Append GlobalStyle with the color palette with css variables
- [x] Apply all css variables where colors have been applied
- [x] Implement the open sans font
- [x] Create top bar with title and logo
- [x] Style Create/Add Form
- [x] Style Recipe Details
- [x] Style Recipe List
- [x] Style Navigation

**Comment by BirkBee** [comment]
I really like to see your team adding color and styling to your app 😍  I'm looking forward to see the results. 

I'm not sure yet about your color choice, but I would like to see the results first. I would've probably went with a lighter and fresher theme, like light green, white or light red. Because I feel like the user might be attracted to a "fresh and light look" for cooking. But as I said I'm curious to see your design applied first

Let's gooo 🚀

**Comment by feivlinus** [comment]
Thank you for your review Birk! :3
We got the color palette by a generator and compared those colors to each other with contrast rating and even used a site which renders basic ui elements based on that palette. We will try this color palette for now and maybe adjust it a bit to make it more brighter or maybe pick another at some point. We have to try it out at our app. I green would also suit good you are right we keep that in mind. Thank you for your suggestions.

**Comment by BirkBee** [comment]
Yes sure! 
Ah okay wow, sounds very good! So you are already deep in planning and you did put a lot of thought into it, sounds very nice! Yes sure, looking forward to see your designed app 🚀
