### ISSUE TITLE
Implement Database

### ISSUE THREAD

**Issue by Shahab-Ziaeian** [feivlinus/fork-yeah#26]
## Value proposition

As a user
I want to have my app data stored in a database
So I can have the same access to my recipes on any device.

## Description

No major changes to the app's appearance or user interface are expected, aside from potential error handling during data fetching.

## Acceptance criteria

 - [ ] The user's recipe including their specific details is stored in the MongoDB database.
 - [ ] Creating, editing or deleting a recipe will be reflected in MongoDB.
       - A new recipe will be stored in MongoDB 
       - Changes will be accepted in the Database
       - Deleted recipes will be removed from MongoDB.
 - [ ] The MongoDB collection for recipes contains all informations generated
       by the user.

## Tasks

- [ ] Create a feature branch
- [ ] Install the MongoDB Atlas driver for the Recipe app
- [ ] Implement code to connect the Recipe app to the MongoDB Atlas database
- [ ] Implement code to fetch recipe data from the MongoDB Atlas database upon loading the Recipe app
- [ ] Implement code to capture user input for changes of recipes
- [ ] Implement code to store user's favorite recipes in a dedicated data structure
- [ ] Upon navigating to the favorites list page, ensure the displayed recipes are consistent with the local favorite list data

**Comment by GoekhanAgkurt** [comment]
Nice User Story 🔥 LGTM 



![Image](https://github.com/feivlinus/fork-yeah/assets/134974986/b82ce8b9-127a-434a-b197-4db204a6f397)
