### ISSUE TITLE
User Story: Create Recipe

### ISSUE THREAD

**Issue by Shahab-Ziaeian** [feivlinus/fork-yeah#4]
## Value proposition

As a user 
I want to create new recipes
to expand the recipe collection 

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/145024927/2ee3ca2e-d8b2-4ce9-81ae-f63bdedcafe1)

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/4e1866f7-0183-4195-9a31-3c6af61d8054)

## Acceptance criteria

- [x] if you click on the plus symbol the create recipe form will be opened on a new page
- [x] all input fields are empty
- [x] if you click on the X icon at the top right the form will be canceled/closed _Note: changed the icon to a cancel button for now.  Do the Icons Issue in an upcoming User Story_ 
- [x] you can fill in a title into the title field
- [x] you can fill in a duration time into the duration time field 
- [x] you can fill in a URL to a image for the recipe
- [x] you can fill in 4 ingredients at the ingredient input field and their amount in the amount input field
- [x] just the title will have a required input field 
- [x] inside the description you can fill out the steps to cook a recipe inside the text field
- [x] if you click on "Add recipe" every field will be checked if it contains valid data, if not an note at the field 
       will be shown, and if everything is alright the form will be submitted ~~and the user gets a note for success~~ _Note: canceled this feature._

## Tasks

- [x] create a feature branch
- [x] append the recipe list with a plus button 
- [x] add a link to the form page to the plus button
- [x] create a form page and component
- [x] create form validation
- [x] create form submit
- [x] put form data into the database

**Comment by vlatkojuric** [comment]
Hey gang,I just wanna leave a note here that I deleted all the question marks from our acceptance criteria text,they are not needed there

**Comment by mbosselmann** [comment]
Hi team fork yeah!
I really like your user story! 👍  
But I have some remarks for you:
- There is an empty code block at the end of the issue. Is that intentional or maybe your template is broken? 🤔 
- It was not clear to me from the acceptance criteria and the wireframes that the form should be on a new page (I only realized this after reading the tasks). It looked to me as if the form would overlap the recipe list. Perhaps this could be emphasized in the acceptance criteria. 
- It would be good to know which input fields are required :)
- And last one: Your last acceptance criteria describes a wonderful process what happens if the form contains valid data or not. It would be really cool to see this flow also in your wireframes.

I hope this does help to improve your user stories much further! 💪 
Feel free to ask me if you have further questions!

**Comment by Shahab-Ziaeian** [comment]
Thank you for your kind feedback. We considered your suggestions and made the adjustments  :)

**Comment by luederb** [comment]
Hey @Shahab-Ziaeian 
We see all the remarks from Mareike implemented in your updated User Story. So it looks good to us 👍

**Comment by feivlinus** [comment]
Changed the third and last acceptance criteria because.
