### ISSUE TITLE
User Story: Delete Recipe

### ISSUE THREAD

**Issue by Shahab-Ziaeian** [feivlinus/fork-yeah#5]
## Value proposition

As a user, 
I want to delete recipes,
to reduce the recipe collection .

## Description

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/96b1ec28-1626-4fed-b049-8bafc318ba0c)

![Image](https://github.com/feivlinus/fork-yeah/assets/8994153/d2f231f0-cd61-429b-9ec3-8f36c204d29c)

## Acceptance criteria

- [ ] when you click on the Delete button, a confirm dialog appears        asking you: "Are you sure you want 
       to delete this recipe ?" 
- [ ] if you click on the ok button the recipe gets deleted and you get        redirected to the recipe list
- [ ] if you click on the Cancel button the confirm dialog disappears and        you stay on the details page

## Tasks

- [ ] create a feature branch
- [ ] create a icon button component inside the recipe detail page
- [ ] create a confirm dialog
- [ ] create delete function which gets called on confirm true

**Comment by vlatkojuric** [comment]
Same here ,all ? were deleted

**Comment by GoekhanAgkurt** [comment]
hey @vlatkojuric @feivlinus  @Shahab-Ziaeian ,

nice user-Story. But who the f* eats pizza soup? 🤢 

We think that you have to add a Wireframe for the confirmation dialog you are listing in the AC so it is clear how to delete a recipe. 

There are a lot of ways to implement a confirm dialog.  Maybe you want specify it in your tasks. 

keep on the good work and bon appetit!  🍕 🥣

**Comment by vlatkojuric** [comment]
Hey Gökhan , thank you for your review, we made the Wireframe changes ,but think it is not necessary to specify in the tasks how we implement the confirm dialog , it would be too long.

Thanks again.

**Comment by ykolomytseva** [comment]
Hello hello @vlatkojuric @feivlinus @Shahab-Ziaeian, we checked your update and it looks good to us 👍
